frontend/controllers/CatalogController.php
<?php
namespace frontend\controllers;

use common\models\Items;
use Yii;
use yii\web\Controller;
use frontend\models\UploadForm;
use yii\web\UploadedFile;
use common\models\User;
use common\models\Plants;
use common\models\PlantClasses;
use common\models\StatItems;
use common\models\PlantSpecies;
use yii\web\ForbiddenHttpException;

/**
 * Site controller
 */
class CatalogController extends Controller
{
    /**
     * @var array of errors while import process
     */



    /**
     * @inheritdoc
     */
//    public function behaviors()
//    {
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['logout', 'signup'],
//                'rules' => [
//                    [
//                        'actions' => ['signup'],
//                        'allow' => true,
//                        'roles' => ['?'],
//                    ],
//                    [
//                        'actions' => ['logout'],
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
//        ];
//    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {

    }

    public function actionSearch()
    {

        return $this->render('search');
    }

    public function actionData()
    {
        \Yii::$app->response->format = 'json';

        $plant_id = Yii::$app->request->get('plant_id',0);

        $params = [];

        if($plant_id){
            $params['plant_id'] = $plant_id;
        }
        $items = Items::find()
            ->with('nursery.region')
            ->where($params)
            ->orderBy('id')->asArray()->all();
        return $items;
    }

    public function actionImport()
    {
        if (Yii::$app->user->can('importPrice')) {
            $model = new UploadForm();
            $errors = [];
            if (Yii::$app->request->isPost) {
                $model->file = UploadedFile::getInstance($model, 'file');
                if ($model->file && $model->validate()) {

                    $inputFileName = $model->file->tempName;
                    try {
                        $inputFileType = \PHPExcel_IOFactory::identify($inputFileName);
                        $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
                        $objPHPExcel = $objReader->load($inputFileName);
                    } catch (Exception $e) {
                        die('Error loading file "' . pathinfo($inputFileName, PATHINFO_BASENAME) . '": ' . $e->getMessage());
                    }
                    $sheet = $objPHPExcel->getSheet(0);
                    $highestRow = $sheet->getHighestRow();
                    $highestColumn = $sheet->getHighestColumn();


                    $currentNursery = User::getNursery(\Yii::$app->user->id);
                    if (!isset($currentNursery)){

                        $errors[] = 'You have no nursery';
                        return $this->render('import', ['model' => $model, 'errors' => $errors]);

                    }
                    //delete items from this nursery
                    Items::deleteAll("nursery_id = :nursery_id", ['nursery_id' => $currentNursery->id]);

                    //delete from statitems if user had loaded his price previously this day
                    date_default_timezone_set('Europe/Kiev');
                    $currTimestamp = getdate(time());
                    StatItems::deleteAll(['YEAR(FROM_UNIXTIME(created_at))' => $currTimestamp['year'],
                        'MONTH(FROM_UNIXTIME(created_at))' => $currTimestamp['mon'],
                        'DAY(FROM_UNIXTIME(created_at))' => $currTimestamp['mday'],
                        'nursery_id' => $currentNursery->id,
                    ]);

                    if (!file_exists(Yii::getAlias('@app/runtime/logs/importlogs/'))) {
                        mkdir(Yii::getAlias('@app/runtime/logs/importlogs/'), 0777, true);
                    }
                    $errorLog = iconv('UTF-8', 'windows-1251', $currentNursery->name) . date('dmY') . '.errorlog';
                    $logFile = fopen(Yii::getAlias('@app/runtime/logs/importlogs/') . $errorLog, 'wt');
                    fwrite($logFile, "Starting import from " . $currentNursery->name . " " . date('d/m/Y') . "\r\n");

                    //  Loop through each row of the worksheet in turn
                    for ($row = 1; $row <= $highestRow; $row++) {
                        //  Read a row of data into an array
                        $rowData = $sheet->rangeToArray('A' . $row . ':' . $highestColumn . $row,
                            NULL,
                            FALSE,
                            FALSE);
                        /**
                         * $inputRecord is an array of Excel data file row
                         * $inputRecord[0][0] - plant_class name_lat, name_ru, name_ua
                         * $inputRecord[0][1] - plants name_lat, name_ru, name_ua
                         * $inputRecord[0][2] - plants cultivar
                         * $inputRecord[0][3] - items landing_type
                         * $inputRecord[0][4] - items height_min, height_max
                         * $inputRecord[0][5] - items width_min, width_max
                         * $inputRecord[0][6] - items girth_min, girth_max
                         * $inputRecord[0][7] - items shtamb
                         * $inputRecord[0][8] - items amount
                         * $inputRecord[0][9] - items price
                         *
                         */

                        $item = new Items();
                        $statItem = new StatItems();
                        $item->nursery_id = $statItem->nursery_id = $currentNursery->id;

                        $plantClass = PlantClasses::getPlantClassByName(trim($rowData[0][0]));
                        if (!$plantClass) {
                            $errors[] = $rowData[0][0] . ' - Plant Class doesnt exist';
                            continue;
                        }


                        $plant_specie = PlantSpecies::getPlantSpeciesByName(trim($rowData[0][1]));
                        if (!$plant_specie) {
                            $errors[] = $rowData[0][1] . ' Plant Specie doesnt exist';
                            continue;
                        } elseif(!(Plants::find()->AndWhere(['is', 'cultivar', null])->AndWhere(['species_id'=>$plant_specie->id])->one())
                                &&
                            (trim($rowData[0][2]) == '')){
                                //if there are not any plants with empty cultivar and cultivar field in import file is empty
                                $errors[] = 'There is no plant with empty cultivar. Please fill cultivar before next import';
                                continue;
                        }
                        // If there is any plant with cultivar type as in import file
                        if ((trim($rowData[0][2]) != '') && (!Plants::findOne(['cultivar' => $rowData[0][2],
                                                                            'species_id' => $plant_specie->id])))
                        {
                            $errors[] = $rowData[0][1] . ' Doesnt have this cultivar ' . $rowData[0][2];
                            continue;
                        }

                        $item->plant_id = $statItem->plant_id = Plants::findOne(['cultivar' => $rowData[0][2],
                                                                                 'species_id'=>$plant_specie->id

                                                                                ])->id;
                            //Plants::find()->Where(['cultivar' => $rowData[0][2]])->andWhere(['name_lat' => $rowData[0][1]])->one()->id;

                        $item->landing_type = $statItem->landing_type = $rowData[0][3];

                        if (isset($rowData[0][4])) {
                            $hminmax = preg_split("/(\/|\?|=|-)/", $rowData[0][4]);
                            if (is_numeric($hminmax[0]) && is_numeric($hminmax[1])) {
                                $item->height_min = $statItem->height_min = $hminmax[0];
                                $item->height_max = $statItem->height_max = $hminmax[1];
                            } else {
                                $errors[] = $rowData[0][4] . ' incorrect height';
                                continue;
                            }
                        } else {
                            $item->height_min = $statItem->height_min = 0;
                            $item->height_max = $statItem->height_max = 0;
                        }

                        if (isset($rowData[0][5])) {
                            $wminmax = preg_split("/(\/|\?|=|-)/", $rowData[0][5]);
                            if (is_numeric($wminmax[0]) && is_numeric($wminmax[1])) {
                                $item->width_min = $statItem->width_min = $wminmax[0];
                                $item->width_max = $statItem->width_max = $wminmax[1];
                            } else {
                                $errors[] = $rowData[0][5] . ' incorrect width';
                                continue;
                            }
                        } else {

frontend/views/catalog/import.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use kartik\widgets\FileInput;
use yii\web\JsExpression;

$this->title = Yii::t('app', 'import.pagetitle');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="row">
    <div class="col-md-12">
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

<?= $form->field($model, 'file')->widget(FileInput::classname(), [
        'name' => 'uploadPrice',
    	'options'=>[
        	//'multiple'=>true,
    		'showPreview' => false,
        ],
   		'pluginOptions' => [
            //'uploadUrl' => Url::to(['/catalog/import']),
            'browseLabel' => Yii::t('app', 'import.browseLabel'),
            'allowedFileExtensions' => ['xls' , 'xlsx' , 'csv'],
            'maxFileCount' => 1,
            'slugCallback' => new JsExpression('function(filename) {
                                return filename;
                                }'
            ),
    	]
    ]);

	Html::submitButton('Upload price', ['class' => 'btn btn-primary', 'name' => 'upload-button']);
?>
    </div>

<?php ActiveForm::end() ?>

<?php
if ($errors) {
    echo '<div class="col-md-6">';
        echo '<div class="panel panel-danger">';
            echo '<div class="panel-heading">';
                echo Html::tag('h3','Errors',['class'=>'panel-title']);
            echo '</div>';
            echo '<div class="panel-body">';
                for ($row = 0; $row <= count($errors) - 1; $row++) {
                    echo Html::tag('li',$errors[$row],['class'=>'list-group-item']);
                }
            echo '</div>';
        echo '</div>';
}

?>
</div>

frontend/views/catalog/search.php
<div id="notify" class='notifications top-right'></div>
<div class="row">
    <div class="col-md-12">
        <table id="translates-table"
               data-toggle="table"
               data-url="/catalog/data"
               data-query-params="queryParams"
               data-show-columns="true"
               data-pagination="true"
               data-search="true"
               data-show-refresh="true"
               data-show-export="true"
               data-page-size="20"
               data-page-list="[10, 20, 50, 100]"
            >
            <thead>
            <tr>
                <th data-field="nursery" data-sortable="true" data-formatter="searchFormatter.nursery" ><?= Yii::t('app', 'field.nursery') ?></th>
                <th data-field="region" data-sortable="true" data-formatter="searchFormatter.region" ><?= Yii::t('app', 'field.region') ?></th>
                <th data-field="landing_type" data-sortable="true"><?= Yii::t('app', 'field.landing_type') ?></th>
                <th data-field="height_min" data-sortable="true" data-formatter="searchFormatter.height" data-align="center"><?= Yii::t('app', 'field.height') ?></th>
                <th data-field="width_min" data-sortable="true" data-formatter="searchFormatter.width" data-align="center"><?= Yii::t('app', 'field.width') ?></th>
                <th data-field="girth_min" data-sortable="true" data-formatter="searchFormatter.girth" data-align="center"><?= Yii::t('app', 'field.girth') ?></th>
                <th data-field="shtamb" data-sortable="true"><?= Yii::t('app', 'field.shtamb') ?></th>
                <th data-field="amount" data-sortable="true"><?= Yii::t('app', 'field.amount') ?></th>
                <th data-field="price" data-sortable="true" data-align="right"><?= Yii::t('app', 'field.price') ?></th>
                <th data-field="price_ds1" data-sortable="true" data-align="right"><?= Yii::t('app', 'field.price_ds1') ?></th>
                <th data-field="price_ds2" data-sortable="true" data-align="right"><?= Yii::t('app', 'field.price_ds2') ?></th>
                <th data-field="price_retail" data-sortable="true" data-align="right"><?= Yii::t('app', 'field.price_retail') ?></th>
            </tr>
            </thead>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="input-group">
        </div>
    </div>
</div>

<div id="confirmation" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="modal-form">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?= Yii::t('backend', 'delete.confirmation') ?>?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-primary" id="delete-confirm">OK</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>


    var searchFormatter = function () {
        var self = {};


        self.region = function (value, row) {
            return row.nursery.region.name;
        };

        self.nursery = function (value, row) {
            return value.name;
        };

        self.height = function (value, row) {
            return value + row.height_max == 0 ? '' : value + '-' + row.height_max;
        };

        self.width = function (value, row) {
            return value + row.width_max == 0 ? '' : value + '-' + row.width_max;
        };

        self.girth = function (value, row) {
            return value + row.girth_max == 0 ? '' : value + '-' + row.girth_max;
        };

        return self;
    }();

    var russianText = '';

    function queryParams(params) {

        if(location.hash){
            var hash = location.hash;
            var filters = JSON.parse(hash.substr(1));
            $.extend(params, filters);
        }
        return params;
    }

    var lastHash = location.hash;
    setInterval(function () {
        if(lastHash != location.hash){
            lastHash = location.hash;
            $('#translates-table').bootstrapTable('refresh', {silent: true});
        }
    },100);

    function operateFormatter(value, row, index) {
        return [
            '<a class="edit ml10" href="javascript:void(0)" title="Edit">',
            '<i class="glyphicon glyphicon-pencil"></i>',
            '</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
            '<a class="remove ml10" href="javascript:void(0)" title="Remove">',
            '<i class="glyphicon glyphicon-remove"></i>',
            '</a>'
        ].join('');
    }

    var w = $('#myModal');


    $('#modal-form').unbind('submit').submit(function(){

        var data = $('#modal-form').serialize();

        $.ajax({
            url: '/catalog/data',
            dataType: 'json',
            data: data,
            type: 'post',
            success: function(){
                w.modal('hide');
                $('#translates-table').bootstrapTable('refresh', {silent: true});

                $('#notify').notify({
                    message: { html: '&nbsp;&nbsp;&nbsp;&nbsp; <b>ОК</b> Запись сохранена! &nbsp;&nbsp;&nbsp;&nbsp; ' },
                    fadeOut: { enabled: true, delay: 3000 }
                }).show();
            }
        });

        return false;
    });


    window.operateEvents = {

        'click .edit': function (e, value, row, index) {
            for(var ind in row) {
                $('#modal-form input[name="row['+ind+']"]').val(row[ind]);
            }
            w.modal('show');
        },

        'click .remove': function (e, value, row, index) {

            e.preventDefault();
            $('#confirmation').data('id', row.id).modal('show');

        }
    };

    $('#add-link').unbind('click').click(function(){

        $('#modal-form input').val('');
        w.modal('show');
        return false;
    });



</script>

frontend/views/catalog/test.php
<?php
use common\models\PlantSpecies;
	echo Yii::getAlias('@app/runtime/logs/importlogs');
    echo '<br>';
echo '<br>';
$plant_specie = PlantSpecies::getPlantSpeciesByName('Picea orientalis');
echo '<br>';
echo $plant_specie->id;
//echo var_dump($plant_specie);
//echo Plants::find()->AndWhere(['is', 'cultivar', null])->AndWhere(['species_id'=>PlantSpecies::getPlantSpeciesByName('Picea orientalis')->one()->id])->one()->id;
//echo '<br>';
//echo Plants::findOne(['cultivar' => 'Glauca',
  //  'species_id' => 49])->id;
?>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input class="form-control" placeholder="Search" type="text">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Well done!</strong> You successfully read <a href="#" class="alert-link">this important alert message</a>.
</div>

<a href="#" class="btn btn-primary btn-lg">Large button</a>
<a href="#" class="btn btn-primary">Default button</a>
<a href="#" class="btn btn-primary btn-sm">Small button</a>
<a href="#" class="btn btn-primary btn-xs">Mini button</a>

<h2>Emphasis classes</h2>
<p class="text-muted">Fusce dapibus, tellus ac cursus commodo, tortor mauris nibh.</p>
<p class="text-primary">Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
<p class="text-warning">Etiam porta sem malesuada magna mollis euismod.</p>
<p class="text-danger">Donec ullamcorper nulla non metus auctor fringilla.</p>
<p class="text-success">Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
<p class="text-info">Maecenas sed diam eget risus varius blandit sit amet non magna.</p>