common/models/Product.php
<?php
/**/
namespace common\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property integer $root
 * @property integer $lft
 * @property integer $rgt
 * @property integer $lvl
 * @property string $name_lat
 * @property string $name_ru
 * @property string $name_ua
 * @property string $plant_foto
 * @property string $icon
 * @property integer $icon_type
 * @property integer $active
 * @property integer $selected
 * @property integer $disabled
 * @property integer $readonly
 * @property integer $visible
 * @property integer $collapsed
 * @property integer $movable_u
 * @property integer $movable_d
 * @property integer $movable_l
 * @property integer $movable_r
 * @property integer $removable
 * @property integer $removable_all
 */
class Product extends \kartik\tree\models\Tree
{
    /* Uploaded image file */
    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['root', 'lft', 'rgt', 'lvl', 'icon_type', 'active', 'selected', 'disabled', 'readonly', 'visible', 'collapsed', 'movable_u', 'movable_d', 'movable_l', 'movable_r', 'removable', 'removable_all'], 'integer'],
            [['lft', 'rgt', 'lvl', 'name_lat'], 'required'],
            [['name_lat', 'name_ru', 'name_ua','plant_foto'], 'string', 'max' => 255],
            [['icon'], 'string', 'max' => 255],
            [['file'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'root' => Yii::t('app', 'Root'),
            'lft' => Yii::t('app', 'Lft'),
            'rgt' => Yii::t('app', 'Rgt'),
            'lvl' => Yii::t('app', 'Lvl'),
            'name_lat' => Yii::t('app', 'Name Lat'),
            'name_ru' => Yii::t('app', 'Name Ru'),
            'name_ua' => Yii::t('app', 'Name Ua'),
            'plant_photo' => Yii::t('app', 'Plant Foto'),
            'file' => Yii::t('app', 'file to upload plant foto'),
            'icon' => Yii::t('app', 'Icon'),
            'icon_type' => Yii::t('app', 'Icon Type'),
            'active' => Yii::t('app', 'Active'),
            'selected' => Yii::t('app', 'Selected'),
            'disabled' => Yii::t('app', 'Disabled'),
            'readonly' => Yii::t('app', 'Readonly'),
            'visible' => Yii::t('app', 'Visible'),
            'collapsed' => Yii::t('app', 'Collapsed'),
            'movable_u' => Yii::t('app', 'Movable U'),
            'movable_d' => Yii::t('app', 'Movable D'),
            'movable_l' => Yii::t('app', 'Movable L'),
            'movable_r' => Yii::t('app', 'Movable R'),
            'removable' => Yii::t('app', 'Removable'),
            'removable_all' => Yii::t('app', 'Removable All'),
        ];
    }

    /**
     * Override isDisabled method if you need as shown in the
     * example below. You can override similarly other methods
     * like isActive, isMovable etc.
     */
    public function isDisabled()
    {
        /*if (Yii::$app->user->identity->username !== 'admin')  {
            return true;
        }
        return parent::isDisabled();*/
    }

    public function getRulatName()
    {
        return $this->name_ru . ' (' . $this->name_lat . ')';
    }

    public function getUalatName()
    {
        return $this->name_ua . ' (' . $this->name_lat . ')';
    }


}

backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\UploadedFile;
use common\models\Product;

class ProductController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public  function actionFileUpload(){

        if (Yii::$app->request->isPost) {
            $request = Yii::$app->request->post();
            $model = Product::findOne(['id' => $request['node_id']]);
            $uploadedFile = UploadedFile::getInstance($model, 'file');
            $uploadedFile->saveAs(Yii::getAlias('@webroot').'/uploads/'.$uploadedFile->name);
            $model->plant_foto = $uploadedFile->name;
            $model->save();
        }
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $result = ['data' => 'success'];
        return $result;
    }

}

backend/views/product/_form.php
<?php
/**
 * @copyright Copyright &copy; Kartik Visweswaran, Krajee.com, 2015
 * @package   yii2-tree-manager
 * @version   1.0.4
 */

use kartik\form\ActiveForm;
use kartik\tree\Module;
use kartik\tree\TreeView;
use kartik\tree\models\Tree;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;
use kartik\widgets\FileInput;
use yii\helpers\Url;
use yii\web\JsExpression;

/**
 * @var View       $this
 * @var Tree       $node
 * @var ActiveForm $form
 * @var string     $keyAttribute
 * @var string     $nameAttribute
 * @var string     $iconAttribute
 * @var string     $iconTypeAttribute
 * @var string     $iconsList
 * @var string     $action
 * @var array      $breadcrumbs
 * @var array      $nodeAddlViews
 * @var mixed      $currUrl
 * @var bool       $showIDAttribute
 * @var bool       $showFormButtons
 */
?>

<?php
/**
 * SECTION 1: Initialize node view params & setup helper methods.
 */
?>
<?php
extract($params);
$isAdmin = ($isAdmin == true || $isAdmin === "true"); // admin mode flag
$inputOpts = [];                                      // readonly/disabled input options for node
$flagOptions = ['class' => 'kv-parent-flag'];         // node options for parent/child


// parse parent key
if (empty($parentKey)) {
    $parent = $node->parents(1)->one();
    $parentKey = empty($parent) ? '' : Html::getAttributeValue($parent, $keyAttribute);
}

// get module and setup form
$module = TreeView::module(); // the treemanager module
$formOptions['id'] = 'kv-' . uniqid();
$form = ActiveForm::begin([   // the active form instance
    'action' => $action,
    'options' => $formOptions
]);
// the primary key input field
if ($showIDAttribute) {
    $options = ['readonly' => true];
    if ($node->isNewRecord) {
        $options['value'] = Yii::t('kvtree', '(new)');
    }
    $keyField = $form->field($node, $keyAttribute)->textInput($options);
} else {
    $keyField = Html::activeHiddenInput($node, $keyAttribute);
}

// initialize for create or update
$depth = ArrayHelper::getValue($breadcrumbs, 'depth');
$glue = ArrayHelper::getValue($breadcrumbs, 'glue');
$activeCss = ArrayHelper::getValue($breadcrumbs, 'activeCss');
$untitled = ArrayHelper::getValue($breadcrumbs, 'untitled');
$name = $node->getBreadcrumbs($depth, $glue, $activeCss, $untitled);
if ($node->isNewRecord && !empty($parentKey) && $parentKey !== 'root') {
    /**
     * @var Tree $modelClass
     * @var Tree $parent
     */
    $depth = empty($breadcrumbsDepth) ? null : intval($breadcrumbsDepth) - 1;
    if ($depth === null || $depth > 0) {
        $parent = $modelClass::findOne($parentKey);
        $name = $parent->getBreadcrumbs($depth, $glue, null) . $glue . $name;
    }
}
if ($node->isReadonly()) {
    $inputOpts['readonly'] = true;
}
if ($node->isDisabled()) {
    $inputOpts['disabled'] = true;
}
if ($node->isLeaf()) {
    $flagOptions['disabled'] = true;
}

// show alert helper
$showAlert = function ($type, $body = '', $hide = true) {
    $class = "alert alert-{$type}";
    if ($hide) {
        $class .= ' hide';
    }
    return Html::tag('div', '<div>' . $body . '</div>', ['class' => $class]);
};

// render additional view content helper
$renderContent = function ($part) use ($nodeAddlViews, $params, $form) {
    if (empty($nodeAddlViews[$part])) {
        return '';
    }
    $p = $params;
    $p['form'] = $form;
    return $this->render($nodeAddlViews[$part], $p);
};
?>

<?php
/**
 * SECTION 2: Initialize hidden attributes. In case you are extending this
 * and creating your own view, it is mandatory to set all these hidden
 * inputs as defined below.
 */
?>
<?= Html::hiddenInput('treeNodeModify', $node->isNewRecord) ?>
<?= Html::hiddenInput('parentKey', $parentKey) ?>
<?= Html::hiddenInput('currUrl', $currUrl) ?>
<?= Html::hiddenInput('modelClass', $modelClass) ?>

<?php
/**
 * SECTION 3: Setup form action buttons.
 */
?>
<div class="kv-detail-heading">
    <?php if (empty($inputOpts['disabled']) || ($isAdmin && $showFormButtons)): ?>
        <div class="pull-right">
            <button type="reset" class="btn btn-default" title="<?= Yii::t('kvtree', 'Reset') ?>">
                <i class="glyphicon glyphicon-repeat"></i>
            </button>
            <button type="submit" class="btn btn-primary" title="<?= Yii::t('kvtree', 'Save') ?>">
                <i class="glyphicon glyphicon-floppy-disk"></i>
            </button>
        </div>
    <?php endif; ?>
    <div class="kv-detail-crumbs"><?= $name ?></div>
    <div class="clearfix"></div>
</div>

<?php
/**
 * SECTION 4: Setup alert containers. Mandatory to set this up.
 */
?>
<div class="kv-treeview-alerts">
    <?php
    $session = Yii::$app->session;
    if ($session->hasFlash('success')) {
        echo $showAlert('success', $session->getFlash('success'), false);
    } else {
        echo $showAlert('success');
    }
    if ($session->hasFlash('error')) {
        echo $showAlert('danger', $session->getFlash('error'), false);
    } else {
        echo $showAlert('danger');
    }
    echo $showAlert('warning');
    echo $showAlert('info');
    ?>
</div>

<?php
/**
 * SECTION 5: Additional views part 1 - before all form attributes.
 */
?>
<?php
echo $renderContent(Module::VIEW_PART_1);
?>

<?php
/**
 * SECTION 6: Basic node attributes for editing.
 */
?>
<?php if ($iconsList == 'text' || $iconsList == 'none'): ?>
    <?php if ($showIDAttribute): ?>
        <div class="row">
            <div class="col-sm-4">
                <?= $keyField ?>
            </div>
            <div class="col-sm-8">
                <?= $form->field($node, 'name_lat')->textInput() ?>
            </div>
        </div>
    <?php else: ?>
        <?= $keyField ?>
        <?= $form->field($node, 'name_lat')->textInput() ?>
    <?php endif; ?>
    <?= $form->field($node, 'name_ru')->textInput() ?>
    <?= $form->field($node, 'name_ua')->textInput() ?>
    <?php
        if ($node->plant_foto){
            echo Html::img('/uploads/'.$node->plant_foto, ['class'=>'file-preview-image', 'alt'=>'The Moon', 'title'=>'The Moon']);
        }
    ?>
    <?= $form->field($node, 'file')->widget(FileInput::classname(),[
           'options' => ['accept' => 'image/*'],
           'pluginOptions' => [
               'uploadUrl' => Url::to(['/product/file-upload']),
               'showRemove' => true,
               'removeClass' => 'btn btn-danger',
               'removeIcon' => '<i class="glyphicon glyphicon-trash"></i> ',
               'uploadExtraData' => [
                   'node_id' => $node->id,
               ],
               'slugCallback' => new JsExpression('function(filename) {
                                return filename;
                                }'
               ),
           ]
        ]);
    ?>
    <?php if ($iconsList === 'text'): ?>
        <div class="row">
            <div class="col-sm-4">
                <?= $form->field($node, $iconTypeAttribute)->dropdownList([
                    TreeView::ICON_CSS => 'CSS Suffix',
                    TreeView::ICON_RAW => 'Raw Markup',
                ], $inputOpts) ?>
            </div>
            <div class="col-sm-8">
                <?= $form->field($node, $iconAttribute)->textInput($inputOpts) ?>
            </div>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="row">
        <div class="col-sm-6">
            <?= $keyField ?>
            <?= Html::activeHiddenInput($node, $iconTypeAttribute) ?>
            <?= $form->field($node, $nameAttribute)->textArea(['rows' => 3] + $inputOpts) ?>
        </div>
        <div class="col-sm-6">
            <?= /** @noinspection PhpUndefinedMethodInspection */
            $form->field($node, $iconAttribute)->multiselect($iconsList, [
                'item' => function ($index, $label, $name, $checked, $value) use ($inputOpts) {
                    if ($index == 0 && $value == '') {
                        $checked = true;
                        $value = '';
                    }
                    return '<div class="radio">' . Html::radio($name, $checked, [
                        'value' => $value,
                        'label' => $label,
                        'disabled' => !empty($inputOpts['readonly']) || !empty($inputOpts['disabled'])
                    ]) . '</div>';
                },
                'selector' => 'radio',
            ]) ?>
        </div>
    </div>
<?php endif; ?>

<?php
/**
 * SECTION 7: Additional views part 2 - before admin zone.
 */
?>
<?= $renderContent(Module::VIEW_PART_2) ?>

<?php
/**
 * SECTION 8: Administrator attributes zone.
 */
?>
<?php if ($isAdmin): ?>
    <h4><?= Yii::t('kvtree', 'Admin Settings') ?></h4>

    <?php
    /**
     * SECTION 9: Additional views part 3 - within admin zone
     * BEFORE mandatory attributes.
     */
    ?>
    <?= $renderContent(Module::VIEW_PART_3) ?>

    <?php
    /**
     * SECTION 10: Default mandatory admin controlled attributes.
     */
    ?>
    <div class="row">
        <div class="col-sm-4">
            <?= $form->field($node, 'active')->checkbox() ?>
            <?= $form->field($node, 'selected')->checkbox() ?>
            <?= $form->field($node, 'collapsed')->checkbox($flagOptions) ?>
            <?= $form->field($node, 'visible')->checkbox() ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($node, 'readonly')->checkbox() ?>
            <?= $form->field($node, 'disabled')->checkbox() ?>
            <?= $form->field($node, 'removable')->checkbox() ?>
            <?= $form->field($node, 'removable_all')->checkbox($flagOptions) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($node, 'movable_u')->checkbox() ?>
            <?= $form->field($node, 'movable_d')->checkbox() ?>
            <?= $form->field($node, 'movable_l')->checkbox() ?>
            <?= $form->field($node, 'movable_r')->checkbox() ?>
        </div>
    </div>

    <?php
    /**
     * SECTION 11: Additional views part 4 - within admin zone
     * AFTER mandatory attributes.
     */
    ?>
    <?= $renderContent(Module::VIEW_PART_4) ?>
<?php endif; ?>
<?php ActiveForm::end() ?>

<?php
/**
 * SECTION 12: Additional views part 5 accessible by all users
 * after admin zone.
 */
?>
<?= $renderContent(Module::VIEW_PART_5) ?>

backend/views/product/index.php
<?php
/* @var $this yii\web\View */
use common\models\Product;
use kartik\tree\TreeView;
?>
<?php
    $query = Product::find()->andFilterWhere(['like', 'name_lat', $name_lat])->addOrderBy('root, lft');
    echo TreeView::widget([
        'query' => $query,
        'headingOptions' => ['label' => 'Растения'],
        'nodeView' => '@backend/views/product/_form',
        'rootOptions' => ['label'=>'<span class="text-primary">Root</span>'],
        'options' => [
            'id' => 'myTree',
        ],
        'fontAwesome' => false,
        'isAdmin' => true,
        'displayValue' => 1,
        'softDelete' => false,
        'showInactive' => false,
        'cacheSettings' => ['enableCache' => true]
    ]);
?>